### ISSUE TITLE
PE() memory leak

### ISSUE THREAD

**Issue by KillerInstinct** [crackinglandia/pype32#11]
Ran into this executable which ended up consuming 32GB of RAM. Not actually sure what the causes is, so including the hash so you can download.

```
~/bug$ cat bug.py
import pype32
data = open("test.exe", "rb").read()
pe = pype32.PE(data=data)

~/bug$ md5sum test.exe
ca25e1bf52a1848512cac8a07c9c0d30  test.exe

~/bug$ pip list | grep pype
pype32 (0.1-alpha4)
```

**Comment by poxyran** [comment]
Hi!, 

can you share the binary?. Upload it to some place like mega, dropbox, etc. so I can take a look.

Thanks!

**Comment by KillerInstinct** [comment]
https://dl.dropboxusercontent.com/u/30244756/bad.zip

Password is infected. It's a malware sample. :)

**Comment by poxyran** [comment]
Thanks!. Btw, have you tried using the "fastLoad" parameter when creating the PE() instance?. Do you get the same behavior?. Maybe, this could be related to https://github.com/crackinglandia/pype32/issues/7

**Comment by KillerInstinct** [comment]
With fastLoad=True, I do not get the same behavior. Not sure if fastLoad compromises any data that I am interested however.

**Comment by poxyran** [comment]
with fastLoad = True you skip the parsing of directories. Imports, exports, etc; will not be included in the final PE() instance. Just the PE headers.

**Comment by brad-sp** [comment]
For the sample in question, we would actually need to parse the directories.  The code using it is here: https://github.com/brad-accuvant/cuckoo-modified/blob/master/lib/cuckoo/common/decoders/njrat.py

**Comment by snemes** [comment]
Provided that njRAT is written in .NET, I guess it is related to the .NET parsing. I'll try to take a look as soon as possible.

**Comment by snemes** [comment]
Actually it was a problem with the Exports directory, contains totally bogus values for most of the fields. This caused Python to try to allocate memory to create a range of number from 0..0x59000000 using the range() function. I replaced the range() call with xrange() to create the range values on the fly using an iterator. Also added an exception handling block around directory parsing to try to fail gracefully whenever an error occurs in one of the directories.

**Comment by poxyran** [comment]
I finally got time to test this. As @snemes said, the binary contains an invalid export table. The fix works fine. I'm closing this one. Reopen if needed.
