### ISSUE TITLE
Extract .NET Resources

### ISSUE THREAD

**Issue by kevthehermit** [crackinglandia/pype32#8]
Read the data from each .NET Resource 

And then parse each resource from a .resources file. - https://msdn.microsoft.com/en-us/library/system.resources.resourcereader(v=vs.110).aspx

![net_resources](https://cloud.githubusercontent.com/assets/2545096/8213841/d8a88ac2-151c-11e5-90b3-3d55907d7d37.png)

WARNING LIVE MALWARE

Have provided some samples for testing 

http://repo.doesntexist.com/public.php?service=files&t=1bf02f3de6eae2762f9c8304fc0af29f

**Comment by kevthehermit** [comment]
This kind of gives the data. But its all the resources in one. 

```
pe = pype32.PE(<path_to_file>)   
m = pe.ntHeaders.optionalHeader.dataDirectory[14].info
    res_data = pe.getDataAtRva(m.directory.resources.rva.value, m.directory.resources.size.value)
```

Tried this but the offset is always returned as 0x0

```
pe = pype32.PE(<path_to_file>)
m = pe.ntHeaders.optionalHeader.dataDirectory[14].info
for i in m.directory.resources.info:
    print i['offset']
    res_data = pe.getDataAtOffset(int(i['offset'], 0), int(i['size'], 0))
    #print res_data.encode('hex')
```

**Comment by poxyran** [comment]
NET support was wrote by @snemes maybe he can give you a better answer. I tested this my self the data showed by CFF explorer in every resources is not present when pype32 parse them.

**Comment by snemes** [comment]
The .NET resource offset is a relative value starting from the resource RVA, so you will actually have to use it like:

``` python
pe = pype32.PE(<path_to_file>)
m = pe.ntHeaders.optionalHeader.dataDirectory[14].info
for i in m.directory.resources.info:
    with open(i["name"], "wb") as f:
        f.write(pe.getDataAtRva(m.directory.resources.rva.value + int(i['offset'], 0), int(i['size'], 0)))
```

I think I'll do some fixes to store the numeric offset and size values in the dict, instead of the hex string, as that makes much more sense (and was probably some debugging remnants I forgot to change), after the fixes you would use:

``` python
pe = pype32.PE(<path_to_file>)
m = pe.ntHeaders.optionalHeader.dataDirectory[14].info
for i in m.directory.resources.info:
    with open(i["name"], "wb") as f:
        f.write(pe.getDataAtRva(m.directory.resources.rva.value + i['offset'], i['size']))
```

**Comment by kevthehermit** [comment]
This is great thank you very much for this and for your work in general :)

Any idea how i could use python in general if not using pype32 to walk through a resources file and extract each sub section?

MSDN suggests that a .resources file can contain multiple resources.

```
ResourceReader Class Enumerates the resources in a binary resources (.resources) file by reading sequential resource name/value pairs.
```

As an example the Lum_1.exe sample has a resource section `b.Resources.resources`
Within b.Resources.resources are 3 sub resource sections. 

RUNPE, SMARTLOGS and URALYA

In this example i am after the b64 string that is in SMARTLOGS

Hope this image helps try and explain what i mean 

![ilspy_resources](https://cloud.githubusercontent.com/assets/2545096/8243482/3f839d16-160f-11e5-9986-ecb6e40bf2a0.png)

Any help would be appreciated. 

Regards

How many times can i say resources :)

**Comment by snemes** [comment]
If you are not using pype32, you have to parse the resources manually. Be warned that it has a complicated and partially undocumented structure, the best material I found was http://www.ntcore.com/files/manifestres.htm, this served as a basis for the implementation.
You can also look at the source code (pype32.py, starting from line 1444) to see my implementation.

The resources.info structure also contains a key named "data" which you can use to access the ManifestResource members either using their name or their index value:

``` python
    pe = pype32.PE(<path_to_file>)
    m = pe.ntHeaders.optionalHeader.dataDirectory[14].info
    for i in m.directory.resources.info:
        for k, v in i["data"].info.iteritems():
            if not isinstance(k, basestring): continue
            with open("{0}_{1}".format(i["name"], k), "wb") as f:
                f.write(v)
```

The support for .NET Manifest Resources is not fully complete as each resource type can have a different format, probably it would be great to add support for the most common formats, but I have not yet had time to search for documentation on the different formats (StringTable, MemoryStream, etc.)

Previously only the first 16 bytes were returned, now I added a patch to have the full data available.

**Comment by kevthehermit** [comment]
Thank you very much. This is working great for what i need to do. 

If i can be of any help in the future please let me know so i can return the favor.

**Comment by poxyran** [comment]
As everything seems to be working fine, I'll close the issue. Reopen if needed.
